export const MONTHS = [
  'Janeiro',
  'Fevereiro',
  'Marçp',
  'Abril',
  'Maio',
  'Junho',
  'Julho',
  'Agosto',
  'Setembro',
  'Outubro',
  'Novembro',
  'Dezembro',
];

export const DAYS = [
  'Segunda',
  'Terça',
  'Quarta',
  'Quinta',
  'Sexta',
  'Sábado',
  'Domingo',
];

export const ALL_DESCRIPTIONS = [
  { icon: '01d.png', description: 'Céu limpo' },
  { icon: '02d.png', description: 'poucas nuvens' },
  { icon: '03d.png', description: 'nuvens dispersas' },
  { icon: '04d.png', description: 'poucas nuvens' },
  { icon: '04d.png', description: 'nuvens cheias' },
  { icon: '09d.png', description: 'chuva' },
  { icon: '09d.png', description: 'relâmpagos' },
  { icon: '09d.png', description: 'sereno' },
  { icon: '09d.png', description: 'sereno' },
  { icon: '09d.png', description: 'sereno' },
  { icon: '09d.png', description: 'chuva fraca' },
  { icon: '09d.png', description: 'sereno forte' },
  { icon: '09d.png', description: 'chuva' },
  { icon: '09d.png', description: 'chuva' },
  { icon: '09d.png', description: 'chuva' },
  { icon: '09d.png', description: 'chuva' },
  { icon: '09d.png', description: 'chuva' },
  { icon: '09d.png', description: 'chuva' },
  { icon: '09d.png', description: 'chuva' },
  { icon: '10d.png', description: 'chuva' },
  { icon: '10d.png', description: 'chuva fraca' },
  { icon: '10d.png', description: 'chuva' },
  { icon: '10d.png', description: 'chuva forte' },
  { icon: '10d.png', description: 'alerta de tempestade' },
  { icon: '10d.png', description: 'alerta de tempestade' },
  { icon: '11d.png', description: 'tempestade' },
  { icon: '11d.png', description: 'tempestade com raios' },
  { icon: '11d.png', description: 'tempestade' },
  { icon: '11d.png', description: 'tempestade' },
  { icon: '11d.png', description: 'tempestade' },
  { icon: '11d.png', description: 'tempestade' },
  { icon: '11d.png', description: 'tempestade' },
  { icon: '11d.png', description: 'tempestade' },
  { icon: '11d.png', description: 'tempestade' },
  { icon: '11d.png', description: 'tempestade' },
  { icon: '13d.png', description: 'neve' },
  { icon: '13d.png', description: 'neve' },
  { icon: '13d.png', description: 'neve leve' },
  { icon: '13d.png', description: 'neve' },
  { icon: '13d.png', description: 'neve forte' },
  { icon: '13d.png', description: 'neve' },
  { icon: '13d.png', description: 'neve' },
  { icon: '13d.png', description: 'neve' },
  { icon: '13d.png', description: 'neve' },
  { icon: '13d.png', description: 'neve' },
  { icon: '13d.png', description: 'neve' },
  { icon: '13d.png', description: 'neve' },
  { icon: '50d.png', description: 'neblina' },
  { icon: '50d.png', description: 'neblina' },
  { icon: '50d.png', description: 'neblina' },
  { icon: '50d.png', description: 'neblina' },
  { icon: '50d.png', description: 'neblina' },
  { icon: '50d.png', description: 'neblina' },
  { icon: '50d.png', description: 'neblina' },
  { icon: '50d.png', description: 'cinza vulcânica' },
  { icon: '50d.png', description: 'rajadas de vento' },
  { icon: '50d.png', description: 'tornado' },
];
